### ISSUE TITLE
MangaFox and MangaHere change their domain

### ISSUE THREAD

**Issue by king37sniper** [AllMangasReader-dev/mirrors#36]
Mangafox change their domain from .me to .la
pls review these commits @braiam https://github.com/AllMangasReader-dev/mirrors/pull/35
.
Temp fix for anyone needs : https://github.com/AllMangasReader-dev/mirrors/issues/36#issuecomment-353263382

**Comment by xietbrix** [comment]
hoping christmas comes early and this gets approved soon >.<

**Comment by Stubbs9410** [comment]
manga site logos were replaced with "?" what do i do

**Comment by king37sniper** [comment]
What site ? @Stubbs9410

**Comment by Stubbs9410** [comment]
all

**Comment by king37sniper** [comment]
U are using the latest version?
1. Try to reload AMR extension
2. Go to chrome-extension://nhjloagockgobfpopemejpgjjechcpfd/popup.html?mode=normal
Click the clock icon (bottom left) and try refresh websites implementations
3. If it still not working, backup ur manga, try to remove and install extension again

It happen to me sometimes
But, after i reload AMR , it's gone

**Comment by Stubbs9410** [comment]
when ill arive home ill try

**Comment by xietbrix** [comment]
the localhost fix doesn't really work unless you plan to run the local server all the time. everytime i reboot it will try to read mirrors and if it's not running AMR breaks :(

really need this mirrors fixed ><

**Comment by Stubbs9410** [comment]
i did all the steps with xampp and reloaded the extension it work now, but after a restart of the pc it brakes again and have to redo it again, ill work with it like this until someone makes a fix.
p.s still cant add new manga from mangafox that is my main one
Thanks for the help @king37sniper

**Comment by king37sniper** [comment]
Because after restart ur pc, u need to run xampp first then ARM next
It's local now, u need to open xampp, start apache module then open chrome (reload arm if u already open chrome)
Then u can quit xampp
.
When u load manga, click Green plus icon on top of the page (in AMR's navigation bar), it's will add new manga from manga fox

**Comment by Stubbs9410** [comment]
i cant find green plus icon can you screenshot it to me or is it a setting that needs to be checked ?

**Comment by king37sniper** [comment]
This is the plus icon : https://i.imgur.com/eyKdl8U.png (try to f5 a few times, it's disappear sometimes)
My settings : https://i.imgur.com/zoF9Kbz.png

**Comment by king37sniper** [comment]
Untick "Automatically add manga in my reading list when I read it. If you uncheck this option, you will have a button in the navigation bar to add the current manga in the list."
It will show the plus icon
.
I don't know how, but right now AMR is automatically add new manga when i read on mangafox
So i tick that options

**Comment by Stubbs9410** [comment]
@king37sniper it works now just nice ty for the help

**Comment by Snipeon** [comment]
Well... after stealing twluo's quick fix for Mangahere, I managed to modify it so that it pretty much works with Mangafox. With one catch. I can't for the life of me figure out how to get the pages to show the entire chapter. The chapter lists show just fine, updates just fine, navigating to the chapter pages from the popup aren't a problem. Even Mangahere has no problem showing the full chapter. BUT THE CHAPTER VIEW FUNCTION JUST REFUSES TO TRIGGER ON MANGAFOX!! This is so triggering... Well, for my quick and dirty fix(stolen from and courtesy of @twluo), just go [here](https://github.com/Snipeon/AMR). I am also looking for people to look into the code to figure out what happened with the chapter view for Mangafox. I'm stuck here.

**Comment by Stubbs9410** [comment]
ok i think mangahere changed from .co to .cc it wont load mangas from mangahere now

**Comment by king37sniper** [comment]
MangaHere fix : https://drive.google.com/open?id=1QZM4EoclZrx61ufFReVR4UmFeZOFCU02
Replace js.rar to C:\xampp\htdocs and reinstall AMR (not reload AMR)
.

> Export ur manga : chrome-extension://nhjloagockgobfpopemejpgjjechcpfd/importexport.html
.
Download and install XAMPP : https://www.apachefriends.org/xampp-files/5.6.32/xampp-win32-5.6.32-0-VC11-installer.exe
.
Then click config in module Apache : https://i.imgur.com/hsvisTp.png
Notepad will open, change "Listen" to 8000 : https://i.imgur.com/qUWXeJZ.png
.
Start module Apache
.
Download this : https://drive.google.com/open?id=1QZM4EoclZrx61ufFReVR4UmFeZOFCU02
Extract js.rar to C:\xampp\htdocs
Extract AMR.rar to everywhere u want
.
Go chrome://extensions/ click load unpacked extension and point it to where u extract AMR.rar
.
Done, u can quit XAMPP now, if sometimes AMR didn't work, Reopen XAMPP start Apache module and reload AMR extensions on chrome
.
Import ur manga and start reading

**Comment by Snipeon** [comment]
ok, I've manage to fix the damn thing. Everything works now. Grab the files from my repo [here](https://github.com/Snipeon/AMR).

**Comment by Stubbs9410** [comment]
it won't load mangas from mangahere when i import it says no chapters were found

**Comment by Snipeon** [comment]
try replacing all instances of https://www.mangahere.co with http://www.mangahere.cc in your export list. Same with mangafox. From https://www.mangafox.me to http://mangafox.la.

**Comment by xietbrix** [comment]
hey sorry to bother snipeon, but what exactly did you fix?

i'm still experiencing the "no chapters found" issue with mangahere. i just removed my mangahere manga and re-added them so it's not an import/export renaming issue with the .co/.cc change.

i'm also getting the mangafox chapters replacing http://mangafox.la with file://mangafox.la

i'm assuming your package includes all of king's fixes and more? i'm losing track of which one is more "complete" :(

**Comment by king37sniper** [comment]
@Stubbs9410 and @xietbrix  It got that "no chapters found" issues too, my way is edit them in notepad+
Ctrl+H and find www.mangahere.cc replace with http://www.mangahere.cc

**Comment by xietbrix** [comment]
does your version work king? :P

**Comment by king37sniper** [comment]
Yes but the "file://" issuse still remaining, i don't know how to fix it
Look the image: https://i.imgur.com/FEYOkFd.png
If u click the red zones, file:// issuse will appear
Right now i'm open new manga by click on the green zone
.
Maybe 
https://github.com/twluo/AMR 
and 
https://github.com/Snipeon/AMR
can fix all the issuse

**Comment by xietbrix** [comment]
wow awesome, thanks for your help king. i didn't know there's a green zone that works atm :D

**Comment by king37sniper** [comment]
I re-try Snipeon version and it working fine 
.
@xietbrix and @Stubbs9410 just download this https://github.com/Snipeon/AMR/archive/develop.zip
Extract develop.zip to everywhere u want
Go chrome://extensions/ remove current AMR then click load unpacked extension and point it to where u extract develop.zip
Import ur manga and it's done, no need xampp any more

**Comment by xietbrix** [comment]
i just tried it and it is successfully marking the chapter as read after it's fully loaded, which is amazing!

however, i'm still getting the file:// error. is that the same for you?

**Comment by king37sniper** [comment]
Snipeon version ? no it's working on me

**Comment by xietbrix** [comment]
i noticed that all of the ones i imported are showing file:// error, but if i delete them and re-add them manually then they start working fine.

maybe something is wrong during import.

i'm still in progress of manually everything back in Orz. will report back here if i see any problems.

**Comment by xietbrix** [comment]
all seems to be working so far.

amazing work and many thanks for king and snipeon!! <3 merry xmas!

**Comment by Stubbs9410** [comment]
ill try them tomorrow at the moment i am not home and ill leave a comment once i tried it

**Comment by Snipeon** [comment]
yep, as @king37sniper said, you would have to grab my copy of AMR from my repo and replace your current extension with it. As for your manga list error, export your list, use something like notepad++ to replace all your mangahere entries with http://www.mangahere.cc and all your mangafox entries to http://mangafox.la. I'm guessing that some of you guys have entries which still point to a wrong address. If you need help with what to replace, feel free to ask.

**Comment by king37sniper** [comment]
Merry xmas 👍

**Comment by twluo** [comment]
Glad my random one nighter was useful for others :)

**Comment by Stubbs9410** [comment]
ok just got home it wotks fine. thanks

**Comment by monkey8113** [comment]
@Snipeon Thanks for your work man! Its like best xmas gift for all of us!
I really appreciate it!
It works again wonderfully!

**Comment by noodle27** [comment]
Oh sweet, it's fixed already. You guys are the best.

But I'm having this problem with MangaHere and not sure if they intentionally made it like that: I can't access the manga directly from URL. 
>When I tried to open a manga from an URL like https://www.mangahere.cc/manga/[manga-name]/ it's always "Unable to connect" (Opera also says "www.mangahere.cc refused to connect").
>Only if I go to their front page https://www.mangahere.cc/ and access to the manga from there then it works fine. 

Maybe because of this my AMR can't update my reading list and all MangaHere entries in my AMR Popup show "No chapters found yet...". 

Anyone else have this problem?

**Comment by king37sniper** [comment]
https won't work now
Try re-install AMR, re-import ur manga list
There were 1 error when during import, it make all manga from mangahere with https

**Comment by noodle27** [comment]
Oh, so they changed back to http now? Thanks man. Appreciate it.

**Comment by king37sniper** [comment]
Yep, they back to http make https is the cause of "No chapters found yet..."

**Comment by dreadlordgaming2000** [comment]
can somebody pls tell me the problem this time
mangahere was replaced with a stupid game site

**Comment by king37sniper** [comment]
OMFG. WTF is that

**Comment by king37sniper** [comment]
RIP my boooookmark

**Comment by king37sniper** [comment]
I got directed to games.la, cos i'm living in asia
Mangahere blocking half of the world

**Comment by xietbrix** [comment]
yyeeeeah gg mangahere. it was nice knowing you.

**Comment by king37sniper** [comment]
I'm using Hotspot Shield Free VPN Proxy, when i need update chapters lists and reading on mangahere
Temporary solutions, maybe they will change it back like mangafox, it's no longer directed to mangazoneapp.com

**Comment by king37sniper** [comment]
It's back boys, gg
But,
> You guys should download all mangas in ur manga list, i had a bad feeling about this, alot of online manga site is going down
